name: Test Themes
on:
  push:
    branches:
      - master
    paths:
      - "starters/**"
      - "themes/**"
      - ".github/**"
      - "cypress/**"
  pull_request:
    branches:
      - master
    paths:
      - "starters/**"
      - "themes/**"
      - ".github/**"
      - "cypress/**"
jobs:
  test_basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn build:basic
          start: yarn serve:basic
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/themes.test.js
  test_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn build:blog
          start: yarn serve:blog
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/themes.test.js
  test_sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn build:sanity
          start: yarn serve:sanity
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/themes.test.js
  test_hydrogen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn build:hydrogen
          start: yarn serve:hydrogen
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/themes.test.js
  test_helium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn build:helium
          start: yarn serve:helium
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/themes.test.js
